name  =input("Enter  Name:  ")
print(Name)
name1 = input("Enter University Name:")
print(name1)
name2= input("Enter your age:")
print(name2)
name3= input("country:")
print(name3)
name4= input("Hobbies:")
print(name4)